version: '3'
services:
  db:
    image: mongo
    volumes:
      - oothmongo:/data/db
  redis:
    image: redis
  next:
    build: ./next
    env_file: ./next/.env.docker
  ooth:
    build: ./ooth
    env_file: ./ooth/.env.docker
  api:
    build: ./api
    env_file: ./api/.env.docker
  proxy:
    build: ./proxy
    env_file: ./proxy/.env.docker
    ports:
      - '$PORT:8080'
volumes:
  oothmongo:
